---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: seasidefm
  name: archives
  labels:
    app: archives
spec:
  replicas: 3
  selector:
    matchLabels:
      app: archives
  template:
    metadata:
      labels:
        app: archives
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: archives
          image: redbirddigital/seaside-archives
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: MONGO_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: archive-secret
                  key: MONGO_CONNECTION
            - name: NEXT_PUBLIC_TWITCH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: archive-secret
                  key: NEXT_PUBLIC_TWITCH_CLIENT_ID
            - name: TWITCH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: archive-secret
                  key: TWITCH_CLIENT_SECRET
            - name: NEXT_PUBLIC_TWITCH_REDIRECT
              valueFrom:
                secretKeyRef:
                  name: archive-secret
                  key: NEXT_PUBLIC_TWITCH_REDIRECT
---
apiVersion: v1
kind: Service
metadata:
  namespace: seasidefm
  name: archives
spec:
  selector:
    app: archives
  ports:
    - name: web-port
      port: 80
      targetPort: 3000
